"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";

type CandlePayload={open_time:number;open:string;high:string;low:string;close:string;volume:string;close_time:number};
type BinanceSymbol={symbol:string;status:string;quoteAsset:string;baseAsset:string;isSpotTradingAllowed?:boolean};
type ExchangeInfo={symbols:BinanceSymbol[]};
type Ticker24h={symbol:string;quoteVolume:string};
type Candidate={symbol:string;timeframe:string;side:"LONG"|"SHORT";score:number;long_score:number;short_score:number;quote_volume:number;last_price:number;rsi_14:number;macd:number;macd_signal:number;volume_ratio:number;reasons:string[]};
type StageDiag={passed:number;dropped:number;dropped_symbols:string[];passed_symbols?:string[]};
type PipelineDiag={backend_input?:StageDiag;dedupe_liquidity?:StageDiag;candles?:StageDiag;volume?:StageDiag;direction?:StageDiag;shortlist?:StageDiag};
type ScannerRun={timestamp:string;status:string;timeframe:string;input_markets:number;prepared_markets?:number;evaluated_markets:number;candidate_count:number;long_candidates:number;short_candidates:number;processing_ms:number;pipeline?:PipelineDiag;candidates:Candidate[]};
type LogsResponse={engine:string;logs:ScannerRun[]};
type FrontStage={passed:number;dropped:number;dropped_symbols:string[];passed_symbols:string[]};

const MARKET_API="https://data-api.binance.vision";
const HISTORY_LIMIT=500;
const MIN_QUOTE_VOLUME=10_000_000;
const SCAN_LIMIT=30;
const AUTO_SCAN_SECONDS=60;
const ALLOWED_QUOTES=new Set(["USDT","USDC","FDUSD"]);
const STABLE_BASES=new Set(["USDT","USDC","FDUSD","TUSD","USDP","DAI","USD1","USDE","PYUSD","BUSD"]);
const TIMEFRAMES=["1m","5m","15m","1h","4h","1d"];

function candleRows(rows:(string|number)[][]):CandlePayload[]{return rows.map(r=>({open_time:Number(r[0]),open:String(r[1]),high:String(r[2]),low:String(r[3]),close:String(r[4]),volume:String(r[5]),close_time:Number(r[6])}))}
async function fetchCandles(symbol:string,timeframe:string){const r=await fetch(`${MARKET_API}/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(timeframe)}&limit=${HISTORY_LIMIT}`,{cache:"no-store"});if(!r.ok)throw new Error(`Unable to load candles for ${symbol}`);return candleRows(await r.json() as (string|number)[][])}
function fmt(v:number|undefined,d=2){return v===undefined||!Number.isFinite(v)?"—":v.toLocaleString(undefined,{maximumFractionDigits:d})}

export default function ScannerPage(){
 const[timeframe,setTimeframe]=useState("15m");const[logs,setLogs]=useState<ScannerRun[]>([]);const[scanning,setScanning]=useState(false);const[progress,setProgress]=useState("Idle");const[error,setError]=useState<string|null>(null);const[autoRun,setAutoRun]=useState(false);const[countdown,setCountdown]=useState(AUTO_SCAN_SECONDS);const[universeDiag,setUniverseDiag]=useState<FrontStage|null>(null);const[liquidityDiag,setLiquidityDiag]=useState<FrontStage|null>(null);const[selectedStage,setSelectedStage]=useState("Universe");const runningRef=useRef(false);const latest=logs[0];
 const loadLogs=useCallback(async()=>{try{const r=await fetch("/api/scanner/logs",{cache:"no-store"});if(!r.ok)throw new Error("Unable to load scanner logs");setLogs((await r.json() as LogsResponse).logs)}catch(e){setError(e instanceof Error?e.message:"Unable to load scanner logs")}},[]);
 useEffect(()=>{void loadLogs()},[loadLogs]);
 const runScanner=useCallback(async()=>{if(runningRef.current)return;runningRef.current=true;setScanning(true);setError(null);setProgress("Loading Binance universe");try{
  const[er,tr]=await Promise.all([fetch(`${MARKET_API}/api/v3/exchangeInfo`,{cache:"no-store"}),fetch(`${MARKET_API}/api/v3/ticker/24hr`,{cache:"no-store"})]);if(!er.ok||!tr.ok)throw new Error("Unable to load Binance scanner universe");
  const exchange=await er.json() as ExchangeInfo;const tickers=await tr.json() as Ticker24h[];const tickerMap=new Map(tickers.map(t=>[t.symbol,Number(t.quoteVolume)]));
  const eligible=exchange.symbols.filter(s=>s.status==="TRADING"&&s.isSpotTradingAllowed!==false&&ALLOWED_QUOTES.has(s.quoteAsset)&&!STABLE_BASES.has(s.baseAsset));
  const eligibleSet=new Set(eligible.map(s=>s.symbol));setUniverseDiag({passed:eligible.length,dropped:exchange.symbols.length-eligible.length,dropped_symbols:exchange.symbols.filter(s=>!eligibleSet.has(s.symbol)).map(s=>s.symbol),passed_symbols:eligible.map(s=>s.symbol)});
  const bestByBase=new Map<string,{symbol:string;baseAsset:string;quoteVolume:number}>();
  for(const s of eligible){const q=tickerMap.get(s.symbol)??0;if(q<MIN_QUOTE_VOLUME)continue;const cur=bestByBase.get(s.baseAsset);if(!cur||q>cur.quoteVolume)bestByBase.set(s.baseAsset,{symbol:s.symbol,baseAsset:s.baseAsset,quoteVolume:q})}
  const uniqueLiquid=[...bestByBase.values()].sort((a,b)=>b.quoteVolume-a.quoteVolume);const liquid=uniqueLiquid.slice(0,SCAN_LIMIT);const liquidSet=new Set(liquid.map(x=>x.symbol));
  const liquidityDropped=eligible.filter(s=>!liquidSet.has(s.symbol)).map(s=>s.symbol);setLiquidityDiag({passed:liquid.length,dropped:liquidityDropped.length,dropped_symbols:liquidityDropped,passed_symbols:liquid.map(x=>x.symbol)});
  const markets:{symbol:string;quote_volume:number;candles:CandlePayload[]}[]=[];for(let i=0;i<liquid.length;i+=5){const batch=liquid.slice(i,i+5);setProgress(`Loading candles ${Math.min(i+batch.length,liquid.length)}/${liquid.length}`);const results=await Promise.all(batch.map(async x=>{try{return{symbol:x.symbol,quote_volume:x.quoteVolume,candles:await fetchCandles(x.symbol,timeframe)}}catch{return{symbol:x.symbol,quote_volume:x.quoteVolume,candles:[] as CandlePayload[]}}}));markets.push(...results)}
  setProgress("Scoring LONG / SHORT candidates");const r=await fetch(`/api/scanner/run?timeframe=${timeframe}&min_quote_volume=${MIN_QUOTE_VOLUME}`,{method:"POST",cache:"no-store",headers:{"content-type":"application/json"},body:JSON.stringify(markets)});if(!r.ok){const b=await r.json().catch(()=>({}));throw new Error(b.detail??"Scanner Engine failed")};await loadLogs();setProgress("Scan complete");setCountdown(AUTO_SCAN_SECONDS)
 }catch(e){setError(e instanceof Error?e.message:"Scanner Engine failed");setProgress("Scan failed")}finally{setScanning(false);runningRef.current=false}},[timeframe,loadLogs]);
 useEffect(()=>{if(!autoRun){setCountdown(AUTO_SCAN_SECONDS);return}const id=window.setInterval(()=>setCountdown(v=>{if(v<=1){void runScanner();return AUTO_SCAN_SECONDS}return v-1}),1000);return()=>window.clearInterval(id)},[autoRun,runScanner]);
 const stages=useMemo(()=>{const p=latest?.pipeline;return[{title:"Universe",rule:"Active Spot + allowed quote + non-stable base",diag:universeDiag},{title:"Liquidity",rule:"One best pair/base → ≥ $10M → top 30 unique",diag:liquidityDiag},{title:"Candles",rule:"Fetch + ≥ 200 closed candles",diag:p?.candles??null},{title:"Volume",rule:"≥ 1.5x vs previous 20",diag:p?.volume??null},{title:"Direction",rule:"RSI + MACD + LONG/SHORT score",diag:p?.direction??null},{title:"Shortlist",rule:"Final eligible candidates",diag:p?.shortlist??null}]},[latest,universeDiag,liquidityDiag]);
 const activeStage=stages.find(s=>s.title===selectedStage)??stages[0];const dropped=activeStage.diag?.dropped_symbols??[];const passedSymbols=activeStage.diag?.passed_symbols??(activeStage.title==="Shortlist"?latest?.candidates.map(c=>c.symbol)??[]:[]);
 return <div className="pageWrap"><div className="pageHeader"><div><p className="eyebrow">Market Intelligence</p><h1>Scanner</h1><p className="muted">Trace exactly where each symbol passes or gets filtered. Full run history remains in Engine Working Log.</p></div><span className="modePill"><span />{scanning?"Scanner running":autoRun?"Auto scan active":"Scanner ready"}</span></div>
 <div className="statGrid"><div className="statCard"><span>Last Scan</span><strong>{latest?new Date(latest.timestamp).toLocaleTimeString():"—"}</strong><small className="neutral">{latest?.timeframe??timeframe} timeframe</small></div><div className="statCard"><span>Candidates</span><strong>{latest?.candidate_count??0}</strong><small className="neutral">{latest?.evaluated_markets??0} evaluated</small></div><div className="statCard"><span>LONG</span><strong className="positive">{latest?.long_candidates??0}</strong><small className="neutral">bullish opportunities</small></div><div className="statCard"><span>SHORT</span><strong className="negative">{latest?.short_candidates??0}</strong><small className="neutral">bearish opportunities</small></div></div>
 <section className="panel" style={{padding:18,marginBottom:14}}><div className="panelHead" style={{alignItems:"flex-start"}}><div><p className="eyebrow">Scanner Pipeline</p><h2>Symbol Trace Pipeline</h2><p className="muted" style={{marginTop:6}}>{progress}</p></div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap",justifyContent:"flex-end"}}><select value={timeframe} onChange={e=>setTimeframe(e.target.value)} disabled={scanning} style={controlStyle}>{TIMEFRAMES.map(tf=><option key={tf}>{tf}</option>)}</select><button onClick={()=>void runScanner()} disabled={scanning} style={runStyle}>{scanning?"Scanning…":"Run Now"}</button><button onClick={()=>{setAutoRun(v=>!v);setCountdown(AUTO_SCAN_SECONDS)}} style={autoRun?autoOnStyle:controlStyle}>{autoRun?"Auto Run ON":"Auto Run OFF"}</button><span className="periodTag">Next scan {autoRun?`${countdown}s`:"—"}</span></div></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(6,minmax(0,1fr))",gap:10,marginTop:18}}>{stages.map((s,i)=><button key={s.title} onClick={()=>setSelectedStage(s.title)} style={{...pipelineCard,...(s.title===selectedStage?pipelineSelected:{})}}><span className="eyebrow">Step {i+1}</span><strong style={{display:"block",margin:"7px 0 5px",fontSize:12}}>{s.title}</strong><span className="muted" style={{fontSize:9}}>{s.rule}</span><div style={{display:"flex",gap:10,marginTop:10,fontSize:10}}><span className="positive">Pass {s.diag?.passed??"—"}</span><span className="negative">Drop {s.diag?.dropped??"—"}</span></div></button>)}</div>
 <div style={tracePanel}><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><strong>{activeStage.title} diagnostics</strong><div className="muted" style={{fontSize:10,marginTop:4}}>{activeStage.rule}</div></div><span className="periodTag">Pass {activeStage.diag?.passed??0} · Drop {activeStage.diag?.dropped??0}</span></div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginTop:12}}><div><div className="positive" style={{fontSize:10,fontWeight:700,marginBottom:7}}>PASSED SYMBOLS</div><div style={symbolBox}>{passedSymbols.length?passedSymbols.join(" · "):"No symbol list for this stage."}</div></div><div><div className="negative" style={{fontSize:10,fontWeight:700,marginBottom:7}}>DROPPED / STUCK HERE</div><div style={symbolBox}>{dropped.length?dropped.join(" · "):"None"}</div></div></div></div>{error&&<p className="negative" style={{marginBottom:0}}>{error}</p>}</section>
 <section className="panel" style={{overflow:"auto"}}><div className="panelHead compact"><div><h2>Last Scan Result</h2><p className="muted" style={{marginTop:5}}>{latest?`${latest.candidate_count} candidates · ${latest.processing_ms} ms backend processing`:"No scanner run yet"}</p></div><span className="periodTag">{latest?`${latest.long_candidates} LONG · ${latest.short_candidates} SHORT`:"Waiting"}</span></div><div style={{minWidth:1250}}><div style={{...rowStyle,color:"#69768a",fontSize:9,textTransform:"uppercase"}}><span>Symbol</span><span>TF</span><span>Side</span><span>Score</span><span>L/S</span><span>24h Quote Vol</span><span>Price</span><span>RSI</span><span>Vol Ratio</span><span>Reasons</span></div>{!latest&&<div style={{padding:28,color:"#78859a",fontSize:12}}>Run Scanner to populate the latest result.</div>}{latest?.candidates.map(r=><div key={`${r.symbol}-${r.side}`} style={rowStyle}><strong>{r.symbol}</strong><span>{r.timeframe}</span><strong className={r.side==="LONG"?"positive":"negative"}>{r.side}</strong><strong>{r.score}</strong><span>{r.long_score}/{r.short_score}</span><span>${fmt(r.quote_volume,0)}</span><span>{fmt(r.last_price,6)}</span><span>{fmt(r.rsi_14,2)}</span><span>{fmt(r.volume_ratio,2)}x</span><span title={r.reasons.join(" · ")}>{r.reasons.join(" · ")||"—"}</span></div>)}</div></section></div>
}

const controlStyle={background:"#0b1118",color:"#dfe7f1",border:"1px solid #263242",borderRadius:7,padding:"8px 10px",cursor:"pointer"} as const;
const runStyle={...controlStyle,background:"#173329",color:"#69e4b8",border:"1px solid #285845",fontWeight:700} as const;
const autoOnStyle={...controlStyle,background:"#182d3c",color:"#77c8ff",border:"1px solid #29506a",fontWeight:700} as const;
const pipelineCard={textAlign:"left",border:"1px solid #1d2a39",borderRadius:10,padding:12,background:"#0a1018",color:"#e8edf6",cursor:"pointer"} as const;
const pipelineSelected={border:"1px solid #3b8068",background:"#102019"} as const;
const tracePanel={marginTop:12,border:"1px solid #1d2a39",borderRadius:10,padding:14,background:"#090f16"} as const;
const symbolBox={minHeight:54,maxHeight:120,overflow:"auto",border:"1px solid #192331",borderRadius:8,padding:10,color:"#9aa7ba",fontSize:10,lineHeight:1.7} as const;
const rowStyle={display:"grid",gridTemplateColumns:"105px 45px 65px 55px 65px 125px 100px 65px 75px minmax(380px,1fr)",gap:10,padding:"10px 14px",borderBottom:"1px solid #171f2a",fontSize:10,alignItems:"center"} as const;
